added article by alex-andrero
razrabs-media/editorial pull request #12
Opened 2022-08-02 04:20 UTC by alex-andrero

Привет, ребят!

Получилось сумбурно. Открыт к любым правкам и советам.

2022-08-02 04:32 UTC, alex-andrero commented
Лейблы не добавил ввиду наличия кучи опыта в TFS, а больше толком нигде :)

Если получится описать как добавлять лейблы в разделе "для хлебушков" - думаю буду благодарен не только я.

2022-08-02 07:43 UTC, StarHamster commented
А такое короткое описание так и задумано, да? :)

Получится что-то типа такого:

# С.Т.Р.Е.С.С. - Совет Тем Релоцировавшимся, Еле Сдерживающим Слезы

> Представь ситуацию.

Тебе 22-25 лет, ты только что закончил(-а) институт и понимаешь, что вот он - момент, когда ты можешь всё. Тебе открыта дорога в дивный новый мир.

2022-08-02 10:18 UTC, CommanderTvis requested changes

2022-08-02 10:18 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Однозначно можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревающих сознание. Другие же только сильнее укрепятся в своих целях,
```suggestion
Можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревавших сознание. Другие же только сильнее укрепят уверенность в них — и в своих собственных целях.
```

2022-08-02 10:24 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Нет, я говорю о большом, масштабном путешествии, испытывающем тебя на прочность, проверяющим твои навыки дипломатии, доброжелательности и умения "понять людей и разделить с ними жизнь". Я говорю об э
Зачем? Почему? Это авторское, не трогай

2022-08-02 10:29 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Меня никогда не пугал страх смерти, или боязнь акул. Мой единственный страх - всеобщее человеческое безумие, потеря осознанности и контроля. Для меня “Не смотрите наверх” куда больше фильм ужасов, че
Согласен, тавтология. Но ты тоже ошибся: «У меня никогда не было страха смерти». И зачем слово «так» переставил? Это авторское, не трогай

2022-08-02 10:32 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Этот текст не несёт большой ценности с технической точки зрения, однако есть однозначная уверенность, что печатая его, я формулирую мысли в головах многих людей, которые не рассчитывали на такой исхо
Зачем перефразировал «есть однозначная уверенность», убрал слово «было» и убрал кавычки последние? Это авторское, не трогай

2022-08-02 10:33 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Тут стоит вспомнить жизнеутверждающее творчество одного из наших современников - режиссера Брэда Бёрда, известного как автора мультика “Рататуй”. Готовить могут все, но великим поваром станут только
Сделал что-то непонятное. Это авторское, не трогай

2022-08-02 10:34 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Однозначно можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревающих сознание. Другие же только сильнее укрепятся в своих целях,
Тоже непонятно зачем это

2022-08-02 10:34 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Этот текст не несёт большой ценности с технической точки зрения, однако есть однозначная уверенность, что печатая его, я формулирую мысли в головах многих людей, которые не рассчитывали на такой исхо
Потому что однозначная уверенность - это плеоназм

2022-08-02 10:36 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Этот текст не несёт большой ценности с технической точки зрения, однако есть однозначная уверенность, что печатая его, я формулирую мысли в головах многих людей, которые не рассчитывали на такой исхо
"Было" - а они куда-то исчезло?

2022-08-02 10:36 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Этот текст не несёт большой ценности с технической точки зрения, однако есть однозначная уверенность, что печатая его, я формулирую мысли в головах многих людей, которые не рассчитывали на такой исхо
Кавычки здесь ничего не делают

2022-08-02 10:38 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Тут стоит вспомнить жизнеутверждающее творчество одного из наших современников - режиссера Брэда Бёрда, известного как автора мультика “Рататуй”. Готовить могут все, но великим поваром станут только
Ну сам почитай: "<...> cтоит вспомнить ворчество режиссера <...>, известного как автора мультика "Рататуй"?

2022-08-02 10:41 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Тут стоит вспомнить жизнеутверждающее творчество одного из наших современников - режиссера Брэда Бёрда, известного как автора мультика “Рататуй”. Готовить могут все, но великим поваром станут только
А так я хотя бы разнес режиссера и мультик по разными приложениям

2022-08-02 10:44 UTC, StarHamster commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Тут стоит вспомнить жизнеутверждающее творчество одного из наших современников - режиссера Брэда Бёрда, известного как автора мультика “Рататуй”. Готовить могут все, но великим поваром станут только
Ну... а у тебя вышло: «<...> cтоит вспомнить творчество режиссера <...>, — мультик "Рататуй"». Стало ещё непонятнее. 

Тогда уж просто «режиссера мультика "Рататуй" Брэда Бёрда»

2022-08-02 10:46 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Однозначно можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревающих сознание. Другие же только сильнее укрепятся в своих целях,
"Укрепиться в своих целях" - лексическая несочетаемость

2022-08-02 10:46 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Однозначно можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревающих сознание. Другие же только сильнее укрепятся в своих целях,
"обуревающих" - неправильное время при "некогда"

2022-08-02 10:47 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Однозначно можно прогнозировать, что определенный процент людей сломается и не привнесет в мир тех замечательных идей, некогда обуревающих сознание. Другие же только сильнее укрепятся в своих целях,
"Однозначно прогнозировать" - лексическая несочетаемость. Прогноз - это всегда что-то не точное на 100%

2022-08-02 14:35 UTC, alex-andrero commented
> Утрата смыслов - проблема современного общества. К этому может привести практически любое внешнее событие. Хочется рассказать, как с этой проблемой справился я.

Добавил заголовок

2022-08-02 14:38 UTC, alex-andrero commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +С конца Февраля 2022-го я словно остался один.
Английский мой - враг мой, конечно)

2022-08-02 14:40 UTC, alex-andrero commented
Лейбл "Мнение" я бы поставил

2022-08-02 17:18 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Утрата смыслов - проблема современного общества. К этому может привести практически любое внешнее событие. Хочется рассказать, как с этой проблемой справился я.
```suggestion
Утрата смыслов — проблема современного общества. К этому может привести практически любое внешнее событие. Хочется рассказать, как с этой проблемой справился я.
```

2022-08-02 17:18 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Всего за 2 недели я остался в незнакомой стране без денег, у меня умер близкий родственник, а затем произошел разрыв в отношениях, в которые я вложил 3 года и много усилий. Помимо прочего, на горизон
```suggestion
Всего за 2 недели я остался в незнакомой стране без денег, у меня умер близкий родственник, а затем произошел разрыв в отношениях, в которые я вложил 3 года и много усилий. Помимо прочего, на горизонте замаячил риск мобилизации, что не особо упрощает положение, а в стране, в которой я нахожусь, при наличии проблем приходится иногда уходить от вопросов о гражданстве, чтобы разблокировать банковские счета или получить страховку для аренды жилья на пару месяцев быстрее.
```

2022-08-02 17:18 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +И всё же я знаю, что продолжать жить стоит хотя бы потому, что просто хочется. Хочется вновь мирного неба над головой, хочется чтобы главной проблемой был недостаточно жирный оффер на работе, а главн
```suggestion
И всё же я знаю, что продолжать жить стоит хотя бы потому, что просто хочется. Хочется вновь мирного неба над головой, хочется, чтобы главной проблемой был недостаточно жирный оффер на работе, а главным счастьем — уверенность в том, что будущим поколениям достается не пепелище, а плацдарм для дальнейшей работы и развития.
```

2022-08-02 17:18 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Возможно, нам давно пора переосмыслить границы между государствами и начать воспринимать мир как единый, живой организм. Нет я не говорю, что нужно «смёрджить» все культуры в одну, так не получится.
```suggestion
Возможно, нам давно пора переосмыслить границы между государствами и начать воспринимать мир как единый, живой организм. Нет, я не говорю, что нужно «смёрджить» все культуры в одну, так не получится. Скорее нужно для себя принять ценность собственной личности и стараться вне зависимости от места и окружения нести в мир то, что мы сами обязались нести.
```

2022-08-04 18:52 UTC, alex-andrero commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Всего за 2 недели я остался в незнакомой стране без денег, у меня умер близкий родственник, а затем произошел разрыв в отношениях, в которые я вложил 3 года и много усилий. Помимо прочего, на горизон
не сказать что я согласен с правкой. Я принципиально хотел уточнение - побыстрее, чтобы имелся эмоциональный подтекст.

2022-08-04 19:33 UTC, CommanderTvis approved these changes
С точки зрения языка все хорошо, по-моему.

2022-08-04 19:35 UTC, CommanderTvis commented on s-t-r-e-s-s/s-t-r-e-s-s.md
> +Всего за 2 недели я остался в незнакомой стране без денег, у меня умер близкий родственник, а затем произошел разрыв в отношениях, в которые я вложил 3 года и много усилий. Помимо прочего, на горизон
Понятно. Я тут скорее подчеркивал, что "побыстрее" имеет четкое значение "немного быстрее", то есть не очень корректно его совмещать с конкретным промежутком времени (насколько быстрее?)

2023-07-27 21:31 UTC, closed without merging