“Tech interviews are bullshit” by Adam Arutyunov
razrabs-media/editorial pull request #17
Opened 2022-08-02 07:47 UTC by AdamArutyunov

2022-08-02 08:43 UTC, CommanderTvis requested changes

2022-08-02 08:43 UTC, CommanderTvis commented on tech-reviews-bullshit/tech-reviews-bullshit.md
> +Ну серьёзно. Большинство технических собеседований, которые я видел и к которым обычно помогают готовиться в разных айти-сообществах, проверяют только один навык — готовиться к  техническим собеседов
```suggestion
Ну серьёзно. Большинство технических собеседований, которые я видел и к которым обычно помогают готовиться в разных айти-сообществах, проверяют только один навык — готовиться к техническим собеседованиям.

```

2022-08-02 08:43 UTC, CommanderTvis commented on tech-reviews-bullshit/tech-reviews-bullshit.md
> +Тем не менее, я готовлюсь к собеседованиям. Причина простая — рынок так сказал. Успешно пройденное техинтервью повышает матожидание зарплаты по итогам найма.
```suggestion
Тем не менее я готовлюсь к собеседованиям. Причина простая — рынок так сказал. Успешно пройденное техинтервью повышает матожидание зарплаты по итогам найма.

```

2022-08-02 08:43 UTC, CommanderTvis commented on tech-reviews-bullshit/tech-reviews-bullshit.md
> +Есть ощущение, что моя ценность в другом — знать, что такое хорошо и делать хорошо. Просто брать и делать. И делегировать технодроч другим людям, которым это нравится. Вместе с относительной фулстечн
```suggestion
Есть ощущение, что моя ценность в другом — знать, что такое хорошо и делать хорошо. Просто брать и делать. И делегировать технодроч другим людям, которым это нравится. Вместе с относительной фулстечностью это позволяет мне запилить хороший — объективно хороший — проект с нуля. При этом я пишу чистый — объективно чистый — код, и понимаю, где находится компромисс между удобством масштабирования и затраченным временем. Если вы думаете, что я не люблю техсобеседования, потому что пишу костыли и говнокод, — это большое заблуждение.
```

2022-08-02 09:02 UTC, vladtenlive commented
Я не редактор и не принимаю решения или участие в ревью, но мне кажется - это больше просто твит с твоим возмущением. Чем полноценный материал

2022-08-02 09:07 UTC, AdamArutyunov commented
Возможно. Я опирался на тег «мнение» и брал пример, например, из сообщества Т—Ж, в котором это отдельная категория, где каждый может в коротком формате написать что-то:

https://journal.tinkoff.ru/toxic-job-opinion/
https://journal.tinkoff.ru/friendship-opinion/

Вероятно, редакции медиа нужно определить какие-то критерии поста исходя из своих убеждений — то есть искать баланс между качеством материала и порогом вхождения в сообщество (и ещё между несколькими критериями).

2022-08-02 09:12 UTC, AdamArutyunov commented
Я за разнообразие форматов, потому что иначе медиа может превратиться в Хабр, где котируются только длинные, развёрнутые посты, а авторы, высказывающие не фэктс, а опиньонс, обычно оказываются политыми говном.

2022-08-07 21:48 UTC, CommanderTvis approved these changes

2022-08-11 07:50 UTC, savolkov commented
Ощущение, что прочитал саммари твитов Фила. Не очень понимаю ценность статьи, но если это подходит под формат – нормас :shipit:

2022-12-09 10:14 UTC, closed without merging