1st article from 2pizza
razrabs-media/editorial pull request #8
Opened 2022-08-01 14:23 UTC by the2pizza

Commercial development

2022-08-01 14:29 UTC, philippranzhin commented
Йо, мы слегка криворукие, у нас не работает так — надо бахнуть пр с папкой, в папке мд файл, и картинка, в мд фале ссылка на картинку

2022-08-01 14:58 UTC, vekseel commented
> > Йо, мы слегка криворукие, у нас не работает так — надо бахнуть пр с папкой, в папке мд файл, и картинка, в мд фале ссылка на картинку
> 
> Одна статья - одна папка? Или можно собрать свою колонку в папке?



> > Йо, мы слегка криворукие, у нас не работает так — надо бахнуть пр с папкой, в папке мд файл, и картинка, в мд фале ссылка на картинку
> 
> Одна статья - одна папка? Или можно собрать свою колонку в папке?

Привет! Пока лучше одна статья - одна папка

2022-08-01 17:56 UTC, StarHamster requested changes

2022-08-01 17:56 UTC, StarHamster commented on commercial/commercial.md
> +
Превью — это первая картинка в md-файле. Нет картинки, нет магии, нет превью
```suggestion

![img](commercial.jpeg)

```

2022-08-01 19:28 UTC, the2pizza commented
@StarHamster  Починил, давайте мерджите уже быстрее )))

2022-08-01 20:26 UTC, CommanderTvis requested changes

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Первый раз я увидел компьютер лет в 8. Помню мои первые ощущения какого-то трепета и внутреннего волнения, разглядывая иконки Моего компьютера и Корзины. Я еще не очень хорошо понимал для чего все эт
```suggestion
Первый раз я увидел компьютер лет в 8. Помню свои первые ощущения какого-то трепета и внутреннего волнения, разглядывая иконки Моего компьютера и Корзины. Я еще не очень хорошо понимал, для чего все это, но уже хорошо знал, что тут можно запустить дум3д и мир снаружи замрет. 
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Вот моя первая работа. Кто-то решился меня нанять и платить настоящие деньги за то, что мне нравится. Вот дураки, я бы делал это бесплатно. Компьютер дал мне свободу. Свободу создавать.
```suggestion
Вот моя первая работа. Кто-то решился меня нанять и платить настоящие деньги за то, что мне нравится. Вот дураки — я бы делал это бесплатно. Компьютер дал мне свободу. Свободу создавать. 
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Картинка ускоряется, места работы меняются, а проблемы и люди остаются примерно те же самые. Всех их объединяет примерно одно и тоже. — Проблемы бизнеса. Нужно заработать денег. Я не создаю, я решаю
```suggestion
Картинка ускоряется, места работы меняются, а проблемы и люди остаются примерно те же самые. Всех их объединяет примерно одно и то же — Проблемы бизнеса. Нужно заработать денег. Я не создаю, я решаю проблемы бизнеса. Если бизнесу дешевле нанять сто человек, а не разработать один красивый алгоритм — он наймет сто человек. Бизнесу по барабану красота и качество технологий, ему абсолютно всё равно на производительность и удобство. Запилить MVP и получить инвестиций побыстрее — вот идеалы современного мира.
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +За это хорошо платят и все что я хочу — получить свою зарплату, закрыть ноутбук и напиться. Сделать как можно меньше, ровно сколько нужно чтоб меня не уволили. Я начал видеть только плохое и в програ
```suggestion
За это хорошо платят, и все что я хочу — получить свою зарплату, закрыть ноутбук и напиться. Сделать как можно меньше, ровно столько, сколько нужно, чтоб меня не уволили. Я начал видеть только плохое и в программировании, и в технологиях. Во мне пропало то самое волнение восьмилетнего пацана перед высшим предметом — компьютером. 
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Я люблю программирование. Я до сих пор восхищаюсь классными языками программирования, дронами, настоящими играми, быстрыми и полезными программами, криптографией и многими другими вещами. Когда я ста
```suggestion
Я люблю программирование. Я до сих пор восхищаюсь классными языками программирования, дронами, настоящими играми, быстрыми и полезными программами, криптографией и многими другими вещами. Когда я сталкиваюсь с такими вещами, во мне опять просыпается тот самый пацан.
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Но я всей душой ненавижу коммерческую разработку. Да, именно так, я стал разделять программирование и коммерческую разработку. В коммерческой разработке все еще прикрываются высшими идеалами, на собе
```suggestion
Но я всей душой ненавижу коммерческую разработку. Да, именно так: я стал разделять программирование и коммерческую разработку. В коммерческой разработке все еще прикрываются идеалами прошлого: на собеседованиях спрашивают про алгоритмы и с большим удовольствием врут сами себе про решение сложных технических задач. Но когда заглядываешь внутрь, хочется рвать волосы — «исторически так сложилось, не трогай». 
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
```suggestion
Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу, поэтому для меня теперь отдельно существуют две вещи — программирование и коммерческая разработка. Смотри, не перепутай!
```

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Первый раз я увидел компьютер лет в 8. Помню мои первые ощущения какого-то трепета и внутреннего волнения, разглядывая иконки Моего компьютера и Корзины. Я еще не очень хорошо понимал для чего все эт
от первого лица "свои" лучше звучит. запятая лишняя

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Картинка ускоряется, места работы меняются, а проблемы и люди остаются примерно те же самые. Всех их объединяет примерно одно и тоже. — Проблемы бизнеса. Нужно заработать денег. Я не создаю, я решаю
более логичный вывод абзаца: прямая ассоциация между современными идеалами и тем, что они собой представляют.

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +За это хорошо платят и все что я хочу — получить свою зарплату, закрыть ноутбук и напиться. Сделать как можно меньше, ровно сколько нужно чтоб меня не уволили. Я начал видеть только плохое и в програ
"высшая вещь" - странное сочетание, которое нигде не встречается, "высший предмет" - звучит явно серьезнее

2022-08-01 20:26 UTC, CommanderTvis commented on commercial/commercial.md
> +Но я всей душой ненавижу коммерческую разработку. Да, именно так, я стал разделять программирование и коммерческую разработку. В коммерческой разработке все еще прикрываются высшими идеалами, на собе
"идеалы прошлого" - чтоб был контраст с теми новыми идеалами выше

2022-08-01 22:04 UTC, the2pizza commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
Эй, ну я понимаю еще что всякие мд правильно оформить, но в мой стиль не надо лезть, ок?

2022-08-02 08:21 UTC, CommanderTvis commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
постараюсь делить ченджсеты на более инвазивные и менее инвазивные. а вообще, в этом и прикол публичного ревью - что любой душнила запятые и двоточие может закинуть

2022-08-02 08:25 UTC, AdamArutyunov commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
Расставлять двоеточия и запятые в соответствии с правилами русского языка — это ок.

Заменять «Смотри не перепутай» на «Смотри, не перепутай!» — это не ок. Потому что получилось совсем другое предложение с другой эмоцией и стилем.

2022-08-02 08:26 UTC, the2pizza commented
Идите на хуй с моего текста

2022-08-02 08:32 UTC, CommanderTvis commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
Иногда парцелляция совсем затрудняет чтение.

2022-08-02 08:33 UTC, CommanderTvis commented on commercial/commercial.md
> +Ты должен играть по принятым правилам. Врать компаниям, врать на собеседовании, врать в резюме, врать самому себе. Иначе ты не получишь свой кеш. И я всей душой это ненавижу. Поэтому для меня теперь
Откатил все инвазивные комментарии.

2022-08-02 09:05 UTC, vladtenlive commented
Another one :)

2022-08-02 10:40 UTC, the2pizza commented
знаете почему заниматься сексом на площади очень плохая идея? - советами замучают

2023-07-27 21:31 UTC, closed without merging